version: '3.8'

services:
  erpnext:
    image: frappe/erpnext:v14
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - ADMIN_PASSWORD=admin
      - SITE_NAME=site1.local
      - DB_ROOT_USER=root
      - INSTALL_APPS=erpnext
    ports:
      - "80:80"
    restart: always
    networks:
      - erp_network

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - erpnext_db:/var/lib/mysql
    networks:
      - erp_network

networks:
  erp_network:
    driver: bridge

volumes:
  erpnext_db:
